version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "3000:3000" 
    # INYECCIÓN DIRECTA: Esto es a prueba de fallos
    environment:
      - MONGO_URI=mongodb://mongodb:27017/demon_threshold
      - JWT_SECRET=demon_threshold_clave_secreta_2026
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend_service
    ports:
      - "80:80" 
    depends_on:
      - backend

volumes:
  mongo_data: